name: CI/CD to Selectel Container Registry

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: latest

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Selectel Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}   # cr.selcloud.ru
          username: ${{ secrets.DOCKER_USERNAME }} # iam-token
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Selectel
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login ${{ secrets.REGISTRY_HOST }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker stop ${{ secrets.CONTAINER_NAME }} || true
            docker rm ${{ secrets.CONTAINER_NAME }} || true
            docker run -d --name ${{ secrets.CONTAINER_NAME }} -p 80:8080 ${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
